# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Apache Isis Add-ons
tagline:          Modules, plugins and add-ons to extend the capabilities of Apache Isis.
url:              http://www.isisaddons.org
paginate:         1
baseurl:          /
author:
  name:           Dan Haywood
  url:            https://twitter.com/dkhaywood
  email:          dan@haywood-associates.co.uk

# Custom vars
# version:          1.0.0
# github:
#   repo:           https://github.com/isisaddons/isisaddons.github.io
  
